version: 2.1

orbs:
  docker: circleci/docker@2.1.1
  python: circleci/python@2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          requirements-file: requirements.txt
      # - run:
      #     command: python -m pytest tests/ -v
      #     name: Run tests

  # build:
  #   docker:
  #     - image: cimg/python:3.9
  #   steps:
  #     - checkout
  #     - setup_remote_docker
  #     - run:
  #         name: Build Docker Image
  #         command: docker build -t ngofficial99/python-cicd:latest .
  #     - persist_to_workspace:
  #         root: ~/project
  #         paths:
  #           - .

  # push:
  #   docker:
  #     - image: cimg/python:3.9
  #   steps:
  #     - attach_workspace:
  #         at: ~/project
  #     - setup_remote_docker
  #     - run:
  #         name: Log in to Docker Hub
  #         command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  #     - run:
  #         name: Push Docker Image (latest)
  #         command: docker push ngofficial99/python-cicd:latest
  #     - run:
  #         name: Push Docker Image (SHA)
  #         command: |
  #           docker tag ngofficial99/python-cicd:latest ngofficial99/python-cicd:$CIRCLE_SHA1
  #           docker push ngofficial99/python-cicd:$CIRCLE_SHA1

workflows:
  version: 2
  
  # Workflow for pull requests and feature branches
  test-workflow:
    jobs:
      - test:
          filters:
            branches:
              ignore: 
                - main
                - master

  # Workflow for main branch
  # main-workflow:
  #   jobs:
  #     - test:
  #         filters:
  #           branches:
  #             only: 
  #               - main
      # - build:
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         only: 
      #           - main
      # - push:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: 
      #           - main
