version: 2.1

orbs:
  docker: circleci/docker@2.1.1
  python: circleci/python@2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          requirements-file: requirements.txt

  build-and-push:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t ngofficial99/python-cicd:latest .
      # - run:
      #     name: Push Docker Image (latest)
      #     command: docker push ngofficial99/python-cicd:latest
      # - run:
      #     name: Push Docker Image (SHA)
      #     command: docker tag ngofficial99/python-cicd:latest ngofficial99/python-cicd:$CIRCLE_SHA1 && \
      #              docker push ngofficial99/python-cicd:$CIRCLE_SHA1

workflows:
  version: 2
  ci-cd-workflow:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - /pull\/[0-9]+/
      - build-and-push:
          requires:
            - test
          filters:
            branches:
              only:
                - main
                - /pull\/[0-9]+/
